;; (defvar type-alist '(("WORK") ("PROGRAM") ("REVIEW") ("ESTIMATE") ("MANAGE") ("MTG") ("MAIL") ("REST") ("OTHERS") ("JOB") ("END") ("")))
(defvar type-alist '(("DEV") ("REVIEW") ("ESTIMATE") ("SCHEDULE") ("MANAGE") ("MTG") ("MAIL") ("REST") ("OTHERS") ("JOB") ("END") ("")))
(defvar project-alist '(("tetsukore") ("myworld") ("loa") ("bog") ("bma") ("kntr") ("mngk") ("sanei")
						("keiba") ("worklog") ("flashQuiz") ("mobasnrt")
						("vslot") ("idepo") ("others") ("rpg") ("")))
(defvar term-alist '(("today") ("week") ("month") ("")))
(defvar task-list '( ;; (content task project)
					;; 今週のタスク
;; 					("technodeソーシャルアプリ案件見積" "WORK" "others")
;; 					("裏世界移動バッチを第三月曜にする改修" "" "kntr")
;; 					("stats_accessの通常版とローテート版の設定の違いなどについてドキュメントまとめる" "OTHERS" "others")
;; 					("bmaアバターセット販売（松田さん手伝い）" "PROGRAM" "bma")
;; 					("bogやりとり" "OTHERS" "bog")
;; 					("bogその他" "" "bog")
					("idepo堤さんからの要望等に対応" "PROGRAM" "idepo")
					("sanei開発" "PROGRAM" "sanei")
					("saneiテスト" "WORK" "sanei")
					("saneiサーバ構築" "WORK" "sanei")
					("sanei残タスク整理" "WORK" "sanei")
					("sanei整理" "WORK" "sanei")
					("python環境整備" "PROGRAM" "myproj")
					("worklog改良" "" "worklog")
					("rpg仕様考える" "OTHERS" "rpg")
					("rpg実装" "PROGRAM" "rpg")
;; 					("LOAプロジェクト作成" "WORK" "loa")
					("mngk改修" "PROGRAM" "mngk")
					("loa開発" "" "loa")
					("Flash勉強" "PROGRAM" "")
					;; 定型タスク
					("REVIEW（他の人の設計、コード、テストのレビュー）" "PROGRAM" "")
					("PAIR_PROGRAM" "PROGRAM" "")
					("新規案件見積" "ESTIMATE" "")
					("既存案件見積" "ESTIMATE" "")
					("管理作業" "MANAGE" "")
					("CONDITION（今日の体調）、mono、today" "OTHERS" "others")
					("MTG" "MTG" "")
					("MAIL" "OTHERS" "")
					("TODO作成" "OTHERS" "others")
					("UNEXPECTED（想定外）" "" "")
					("CONCERN" "OTHERS" "others")
					("TASKS（tasksを確認）" "OTHERS" "others")
					("TOMORROW" "OTHERS" "others")
					("LUNCH" "REST" "others")
					("REST" "REST" "others")
					("DINNER" "REST" "others")
					("FRIDAYTALK" "OTHERS" "others")
					("TASK_REVIEW（今週の振り返り）" "OTHERS" "others")
					("SCHEDULE（来週の予定）" "OTHERS" "others")
					("TASKREPORT（タスク状況報告作成）" "OTHERS" "others")
					("MISC（雑多な事）" "" "")
					("END" "END" "others")))
(provide 'my-worklog-conf)
