;; (defvar type-alist '(("WORK") ("PROGRAM") ("REVIEW") ("ESTIMATE") ("MANAGE") ("MTG") ("MAIL") ("REST") ("OTHERS") ("JOB") ("END") ("")))
(defvar type-alist '(("DEV") ("REVIEW") ("ESTIMATE") ("SCHEDULE") ("MANAGE") ("MTG") ("MAIL") ("REST") ("OTHERS") ("JOB") ("END") ("")))
(defvar project-alist '(("tetsukore") ("myworld") ("loa") ("bog") ("bma") ("kntr") ("mngk") ("sanei")
						("keiba") ("worklog") ("flashQuiz") ("mobasnrt")
						("vslot") ("idepo") ("others") ("rpg") ("")))
(defvar term-alist '(("today") ("week") ("month") ("")))
(defvar task-list '( ;; (content task project)
					;; 今週のタスク
					;; 定型タスク
					("REVIEW（他の人の設計、コード、テストのレビュー）" "PROGRAM" "")
					("PAIR_PROGRAM" "PROGRAM" "")
					("新規案件見積" "ESTIMATE" "")
					("既存案件見積" "ESTIMATE" "")
					("管理作業" "MANAGE" "")
					("CONDITION（今日の体調）、mono、today" "OTHERS" "others")
					("MTG" "MTG" "")
					("MAIL" "OTHERS" "")
					("TODO作成" "OTHERS" "others")
					("UNEXPECTED（想定外）" "" "")
					("CONCERN" "OTHERS" "others")
					("TASKS（tasksを確認）" "OTHERS" "others")
					("TOMORROW" "OTHERS" "others")
					("LUNCH" "REST" "others")
					("REST" "REST" "others")
					("DINNER" "REST" "others")
					("FRIDAYTALK" "OTHERS" "others")
					("TASK_REVIEW（今週の振り返り）" "OTHERS" "others")
					("SCHEDULE（来週の予定）" "OTHERS" "others")
					("TASKREPORT（タスク状況報告作成）" "OTHERS" "others")
					("MISC（雑多な事）" "" "")
					("END" "END" "others")))
(provide 'my-worklog-conf)
